// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  // Hanya android & ios
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8c7aQ13p6xk3ApbA2_ZMrhDtrkbgH50g',
    appId: '1:725555508249:android:9c488665b0195b1745e688',
    messagingSenderId: '725555508249',
    projectId: 'fp-pppl',
    storageBucket: 'fp-pppl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAuRQypLIyrwno3_jJRVSVNhLwnw53R_k',
    appId: '1:725555508249:ios:1b4f4675e516d1f145e688',
    messagingSenderId: '725555508249',
    projectId: 'fp-pppl',
    storageBucket: 'fp-pppl.firebasestorage.app',
    iosBundleId: 'com.example.laundryin',
  );

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB9fRjaNZ_bTdSpDZP8nEuFdl77fqnktsE',
  //   appId: '1:725555508249:web:129aa495a1d4a1f545e688',
  //   messagingSenderId: '725555508249',
  //   projectId: 'fp-pppl',
  //   authDomain: 'fp-pppl.firebaseapp.com',
  //   storageBucket: 'fp-pppl.firebasestorage.app',
  //   measurementId: 'G-D3WD7XWVB9',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBAuRQypLIyrwno3_jJRVSVNhLwnw53R_k',
  //   appId: '1:725555508249:ios:1b4f4675e516d1f145e688',
  //   messagingSenderId: '725555508249',
  //   projectId: 'fp-pppl',
  //   storageBucket: 'fp-pppl.firebasestorage.app',
  //   iosBundleId: 'com.example.laundryin',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyB9fRjaNZ_bTdSpDZP8nEuFdl77fqnktsE',
  //   appId: '1:725555508249:web:713a46bf4e51d1ef45e688',
  //   messagingSenderId: '725555508249',
  //   projectId: 'fp-pppl',
  //   authDomain: 'fp-pppl.firebaseapp.com',
  //   storageBucket: 'fp-pppl.firebasestorage.app',
  //   measurementId: 'G-08MT44LHV9',
  // );
}